var dataSet = [
    ["TWEWY(DS)", "Action", "Yes", "Really unqique 2 screen combat where you control 2 characters at once. Interesting story, fun style", "Yes"],
    ["Botw", "Open World", "No", "The definitive open world game that set the standard for the genre", "Yes"],
    ["Persona 5", "Turn Based", "Yes", "Very stylish, fun turn based combat, good writing, enjoyable time management system", "Yes"],
    ["Bravely default", "Turn Based", "Yes", "Really solid turn based JRPG, insteresting brave/boost mechanic", "Yes"],
    ["Octopath traveler", "Turn Based", "Yes", "Really solid JRPG, very refined boost mechanic", "Yes"],
    ["Wind waker", "Action", "No", "If I had to pick 1 traditional Zelda game, it would be this one", "Yes"],
    ["Doom 2016", "FPS", "No", "Everything I could want in an FPS", "Yes"],
    ["Cyber 2077/phantom liberty", "FPS", "No", "After all patches, Incredible gameplay, story, and graphics", "Yes"],
    ["Borderlands 2", "FPS", "No", "Best looter shooter I've played. Great Coop game", "Yes"],
    ["Paranormasite", "Visual Novel", "No", "Incredibly interesting mystery/horrer visual novel", "Yes"],
    ["Hollow knight", "Metroidvania", "No", "The combat based metroidvania that set the standard for the genre", "Yes"],
    ["Ori and the blind forest", "Metroidvania", "No", "The platforming based metroidvania that set the standard for the genre", "Yes"],
    ["Omori", "Turn Based", "No", "Horrer RPG maker game, really good story", "Yes"],
    ["Undertale", "RPG", "No", "Indie title with incredible story telling", "Yes"],
    ["Kh2", "Action", "Yes", "Some of the best action combat out there. Lot of Disney though, not to my tastes", "Yes"],
    ["Xenoblade 3", "MMO-Like", "Yes", "Incredible unqique combat system with great music", "Yes"],
    ["Halo 2", "FPS", "No", "My favorite Halo, has dual wielding, great story, and great gameplay", "Yes"],
    ["Fire emblem three houses", "SRPG", "Yes", "Incredible strategy RPG. Really fun system to upgrade units", "Yes"],
    ["Okami", "Action", "No", "Incredible art style, unique combat system with brush techniques", "Yes"],
    ["Sonic adventure 2 battle", "Platforming", "No", "Favorite sonic game from my childhood. Fast and fun platforming", "Yes"],
    ["Child of light", "Action Bar", "No", "Incredible art style and music. Difficulty balance is also amazing.", "Yes"],
    ["Monster hunter world", "Action", "No", "Single player game I've put the most hours in to. Fun coop, deep combat system", "Yes"],
    ["Sekiro", "Action", "No", "My favorite from software game. Fast and difficult", "Yes"],
    ["Pokemon legends arceus", "Turn Based", "Yes", "Best pokemon game in my opinion", "Yes"],
    ["Voice of cards isle of dragon", "Turn Based", "Yes", "Incredibly enjoyable writing, good art, decent combat", "Yes"],
    ["Osu", "rhythm", "No", "Best rhythm game I've played. BUT I haven't played a lot, low bar", "Yes"],
    ["Transistor/bastion", "Turn Based/Action", "No", "My favorite Supergiant game. Beautiful art style and music, good combat", "Yes"],
    ["Minecraft", "Sandbox", "No", "The classic sandbox experience", "Yes"],
    ["Celeste", "Platforming", "No", "Best platformer I've played, really well designed with tight controls", "Yes"],
    ["Hifi-rush", "Action", "No", "Unique rhythm based action game. Definitely worth your time", "Yes"],
    ["Doki doki literature club", "Visual Novel", "Yes", "Great Visual Novel with a twist", "Yes"],
    ["Ff7 rebirth", "Action", "Yes", "Incredible combat system, some of the best I've seen. Fun enough world", "Yes"],
    ["Danganronpa 2", "Visual Novel", "Yes", "Good visual novel with some fun twists", "Yes"],
    ["AI Somnium files", "Visual Novel", "Yes", "Visual Novel with fun writing", "Yes"],
    ["River city girls 2", "Action", "Yes", "Best couch coop action game you can play with your friend", "Yes"],
    ["Portal 2", "Puzzle", "No", "The classic puzzle game, good story, good puzzles, has coop", "Yes"],
    ["Hyper light drifter", "Action", "No", "Incredible pixel art action game, real fun", "Yes"],
    ["Bo: Path of the Teal Lotus", "Metroidvania", "No", "Beautiful artstyle, good combat and movement", "No"],
    ["Nine Sols", "SRPG/Visual Novel", "No", "Some of the best storytelling you'll ever see", "No"],
    ["Raincode", "Visual Novel", "Yes", "Fun mysteries", "No"],
    ["FF15", "Action", "No", "Really fun combat, good music and graphics", "No"],
    ["Journey", "Platformer", "No", "Great visuals and music. Calming and nothing crazy", "No"],
    ["Gris", "Metroidvania", "No", "Good visuals and music, ok platforming", "No"],
    ["Ender lilies", "Metroidvania", "No", "Animations look rough but great gameplay and music. Visuals are fine", "No"],
    ["Zelda echoes of Wisdom", "Open World", "No", "Very fun small scale zelda. Pretty creative", "No"],
    ["13 sentinels", "SRPG/Visual Novel", "Yes", "Some of the best storytelling you'll ever see.", "No"],
    ["Slay the Princess", "Visual Novel", "Yes", "Fun storytelling with you vs the narrator. Fun hand drawings", "No"],
    ["Battle Block Theature", "Platformer", "No", "Funny and real fun coop platformer", "No"],
    ["A hat in time", "Platformer", "No", "Fun platformer. Not the tightest movement but still good", "No"],
    ["Mario Sunshine", "Platformer", "No", "Best 3D platformer in my opinion", "Yes"],
    ["Tales of Berseria", "Action", "Yes", "Real fun writing, ok combat", "No"],
    ["Bloodborne", "Action", "No", "My favorite From Software game after sekiro. Difficult and fast paced", "No"],
    ["Elden Ring", "Open World", "No", "Incredible open world, incredible visuals, real cheesy build vary difficulty greatly", "No"],
    ["Windblown", "Rougelite", "No", "Most fun coop roguelite I've played", "Yes"],
    ["Bomb Rush Cyberfunk", "Platformer", "No", "Real fun movement parkour game. Not too much compeititon in this genre", "Yes"],
    ["Mirror's Edge", "Platformer", "No", "First person platformer. Better than the sequel", "No"],
];


new DataTable('#videogame', {
    columns: [
        { title: 'Videogame Name', width:100, height:100, fillspace:true },
        { title: 'Genre', width:100, height:100, fillspace:true },
        { title: 'Is anime?', width:100, height:100, fillspace:true },
        { title: 'Comments', width:100, height:100, fillspace:true },
        { title: 'Best of its kind?', width:100, height:100, fillspace:true },
    ],
    data: dataSet,
    paging: false,
    scrollCollapse: true,
    scrollY: '65vh',
    order: [[4, 'desc']]
});